In [7]:
# simple python lists 
height = [1.4,2.5,4.6,5.7,7.8]
weight = [65,47,68,86,67]

# To find BMI we have to find weight[i]/height[i]**2 for every item

# we can not directly use -> weight/height ** 2
weight/height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

# Numpy is the solution
**It provides its array similar to python lists but with strong functionalities**

In [5]:
import numpy as np
height = [1.4,2.5,4.6,5.7,7.8]
weight = [65,47,68,86,67]
height = np.array(height)
weight = np.array(weight)
weight/height ** 2


array([33.16326531,  7.52      ,  3.21361059,  2.6469683 ,  1.10124918])

In [12]:
# if we store multiple data types in numpy array they all becomes strings
L =[1 , True , "Hello" ,2.4]
numpy_L = np.array(L)
print(numpy_L)
print(type(numpy_L[1]))


['1' 'True' 'Hello' '2.4']
<class 'numpy.str_'>


In [ ]:
print(type(L[1])) # original one 

<class 'bool'>


In [14]:
# another differnce of +
x = [1,2,3,4,5]
x+x

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
numpy_x = np.array(x)
numpy_x + numpy_x  # actual addition 

array([ 2,  4,  6,  8, 10])

In [11]:
# ascii or unicode value in python is deteected by ord() function
print(ord("A"))
print(chr(ord("A")))

65
A


In [19]:
simple_lst = [[1,2,3,4,5] , [6,7,8,9,10]]
newLst = np.array(simple_lst)
print(newLst.shape) # tell rows and cols for 2d or more dimensional array
print(type(newLst))
simple_lst[0][1]

print(newLst[0][1])
 # OR For numpy array
print(newLst[0,1])

(2, 5)
<class 'numpy.ndarray'>
2
2


In [21]:
print(newLst[0 , :]) # full row1 
print(newLst[: , 0:2]) # all rows with only 0th and 1th column
print(newLst[1 , :]) # 1th row with all colums
sum(newLst) # sum of rows 

[1 2 3 4 5]
[[1 2]
 [6 7]]
[ 6  7  8  9 10]


array([ 7,  9, 11, 13, 15])