In [1]:
# numpy array -> homogeneous array 
import numpy as np
np_list = np.array([1,2,3,4,5])  # -> vector
print(np_list)
print(type(np_list))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# dtype 
print(np.array([0,1,2,3] , dtype=bool))

[False  True  True  True]


In [3]:
print(np.array([0,1,2,3,4] , dtype=float))

[0. 1. 2. 3. 4.]


In [4]:
lst2 = np.array([[1,2,3,4,5]  , [6,7,8,9,10]])
print(lst2) # -> matrix 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
lst3 = np.array([[[1,2],[3,4] ] , [[5,6] , [7,8]]])
print(lst3)   # -> tensor 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# arange similar to range in python but not an iterator provides an ndaray
print(np.arange(1,5))
print(np.arange(1,11,2)) 

[1 2 3 4]
[1 3 5 7 9]


In [7]:
# reshape mostly used with arange
s = np.arange(1,13).reshape(3,4) # 3*4 grid
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
print(np.zeros(4))
np.zeros((2,2))

[0. 0. 0. 0.]


array([[0., 0.],
       [0., 0.]])

In [10]:
# np.random module
print(np.random.rand(2,2))
 # OR 
print(np.random.random((2,2)))

[[0.17955795 0.28354074]
 [0.82609889 0.71782303]]
[[0.39938328 0.08051531]
 [0.40335625 0.38395668]]


In [11]:
# linspace -> for linear space with equal distributions
print(np.linspace(-10,10,5)) # lower range , upper range , points 
print(np.linspace(-10 , 10 , 5 , dtype=int))

[-10.  -5.   0.   5.  10.]
[-10  -5   0   5  10]


In [12]:
x = np.linspace(-10,10,5 )
print(x)
print(type(x))

[-10.  -5.   0.   5.  10.]
<class 'numpy.ndarray'>


In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# attributes 
x1 = np.arange(10 )
x2 = np.arange(10).reshape(2,5)
x3 = np.arange(8).reshape(2,2,2)

In [15]:
# ndim -> gives dimension 1d ,2d, 3d .... nd
print(x1)
print(x1.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [16]:
print(x2.ndim)
print(x2)

2
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
# shape -> gives shape
print(x1.shape) # 1d array eith 10 items
print(x2.shape)
print(x3.shape)  # 2 2d arays 

(10,)
(2, 5)
(2, 2, 2)


In [18]:
# itemsize 
print(x1.itemsize) # bytes 
x4 = np.arange(2 , dtype= bool)
print(x4.itemsize)

8
1


In [19]:
# for diagonal matrix to be formed or to get diagonal
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]
# GETTING DIAGONAL

print(np.diag(x)) # main diagonla k = 0
print(np.diag(x  , k = 1)) # upper diagonal
print(np.diag(x ,k = -1 )) # lower diagonal


[1 5 9]
[2 6]
[4 8]


In [20]:
# generating a 2d array
lst = [1,2,3]
print(np.diag(lst)) # square matrix
print(np.diag(lst , k = 1)) # 4*4 grid 

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [21]:
# simple python lists 
x = [[1,2,] ,
     [3,4]]
x*2
x = [1,2]
x*2

[1, 2, 1, 2]

In [22]:
# Numpy deals it aritmetically
print(x2)
print(x2 * 2)
print(x2 >> 1) # right shift


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 1 1 2]
 [2 3 3 4 4]]


In [23]:
# Relational operators
s = []
x2 > 5 # item wise comparison 

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [24]:
# new numpy array
lst = np.random.rand(3,3) # range 0 to 1 (inclusive )
print(lst)
lst = np.round(lst*100 )  # multiplying each item bu 100
lst = lst.astype(np.int64) # chabge type to int 
print(lst)


[[0.04136663 0.65592314 0.42066008]
 [0.21299649 0.73318353 0.66654995]
 [0.13722499 0.80944695 0.82579468]]
[[ 4 66 42]
 [21 73 67]
 [14 81 83]]


In [25]:
# max / min / prod
np.sum(lst , axis= 1) # axis = 0 for columns and 1 for row wise
np.max(lst , axis= 0) # column wise 

array([21, 81, 83])

In [26]:
# statistics basics
a = np.array([4,5,3,2,1])
print(np.mean(a)) # average 
print(np.median(a)) # middle value after sorting data
print(np.std(a)) # standard deviation 
print(np.var(a)) # variance
print(np.var(np.array([1,1,1,1]))) # var is determine as feet^2 if unit is feet
print(np.std(np.array([1,1,1,1])))# std is just square root of var

3.0
3.0
1.4142135623730951
2.0
0.0
0.0


In [27]:
# looping 
x2
for i in x2:
    print(i) # print each 1d array inside 2d array 

[0 1 2 3 4]
[5 6 7 8 9]


In [28]:
x3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
for i in x3:
    print(i) # each 2d array inside 3d array 

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [30]:
# for looping item wise 
for i in np.nditer(x2):
    print(i , " " ,end='')

0  1  2  3  4  5  6  7  8  9  

In [31]:
for i in x2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9


In [32]:
# transpose
x2.transpose()
# OR
np.transpose(x2)
# OR
x2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [33]:
# ravel -> to convert any nd array in 1d
new_x3 = x3.ravel()
new_x3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
x2[0,] 
#OR
x2[0,:]
x2[0]

array([0, 1, 2, 3, 4])