In [31]:
import numpy as np

**Create a random 3x4 matrix with value between 0-100. And perform below task**
1. Sort this matrix. np.sort()
2. Sort this matrix based on values in 2nd column.
3. Sort this matrix based on max value in each row.
4. Sort based on elements value.

In [32]:
arr = np.random.randint(1,100,size=(3,4))
arr

array([[70, 88, 40, 14],
       [89, 94, 75, 36],
       [52, 48, 18, 71]], dtype=int32)

In [33]:
# sort
np.sort(arr)

array([[14, 40, 70, 88],
       [36, 75, 89, 94],
       [18, 48, 52, 71]], dtype=int32)

In [34]:
# Sort this matrix based on values in 2nd column.
mask = np.sort(arr[:,1]).reshape(-1,1)
mask = np.argsort(arr[:,1])
mask
arr[mask]

array([[52, 48, 18, 71],
       [70, 88, 40, 14],
       [89, 94, 75, 36]], dtype=int32)

In [35]:
# Sort this matrix based on max value in each row.
arr

array([[70, 88, 40, 14],
       [89, 94, 75, 36],
       [52, 48, 18, 71]], dtype=int32)

In [36]:
new_arr =sorted(arr,key=lambda row : max(row)) # type  is list
print(type(arr))
new_arr = np.array(new_arr)
new_arr

<class 'numpy.ndarray'>


array([[52, 48, 18, 71],
       [70, 88, 40, 14],
       [89, 94, 75, 36]], dtype=int32)

In [37]:
np.sort(arr , axis= None).reshape(np.shape(arr))

array([[14, 18, 36, 40],
       [48, 52, 70, 71],
       [75, 88, 89, 94]], dtype=int32)

**Q-2: There is an array of marks of 5 students in 4 subjects.**
**Further you are asked to perform below task.**
1. Add marks every student of an extra subject in the same array.
2. Add two new students marks in respective 5 subjects.(one subject added in above task)
3. Add extra column with sum of all subjects(5-subjects) marks
4. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
**Note: Change dimension of arrays during concatenation or appending if required.**

In [53]:
rng = np.random.default_rng()
arr = rng.random((5,4))*100 
arr = arr.astype(np.uint32)

In [54]:
# add a new subjects column of students
newSbj = np.array([36,74,64,37,86]).reshape(-1,1)
stdMarks = np.concatenate((arr,newSbj) , axis=1)
stdMarks

array([[45, 84, 92, 62, 36],
       [98, 17, 66, 54, 74],
       [39,  5,  5,  9, 64],
       [45, 10,  5, 35, 37],
       [25, 78, 72, 36, 86]])

In [55]:
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
rec1 = np.expand_dims(rec1,axis=0) # axis mean position where you want expantion 0 means here 1 row only 
rec2 = np.expand_dims(rec2,axis=0)
# or
# rec1 = np.rehsape(rec1 , (1,-1))
stdMarks = np.concatenate((stdMarks , rec1 , rec2) ,axis= 0)
stdMarks

array([[45, 84, 92, 62, 36],
       [98, 17, 66, 54, 74],
       [39,  5,  5,  9, 64],
       [45, 10,  5, 35, 37],
       [25, 78, 72, 36, 86],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [56]:
# add total marks col for each std 
totalMarks = np.sum(stdMarks , axis=1 , keepdims=True)
stdMarks = np.concatenate((stdMarks , totalMarks) , axis=1)
stdMarks

array([[ 45,  84,  92,  62,  36, 319],
       [ 98,  17,  66,  54,  74, 309],
       [ 39,   5,   5,   9,  64, 122],
       [ 45,  10,   5,  35,  37, 132],
       [ 25,  78,  72,  36,  86, 297],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [57]:
# sort based on total marks 
index= np.argsort(stdMarks[:,-1])
index
#now use this mask
stdMarks[index][::-1] # final sorted stds based on total marks

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 45,  84,  92,  62,  36, 319],
       [ 98,  17,  66,  54,  74, 309],
       [ 25,  78,  72,  36,  86, 297],
       [ 45,  10,   5,  35,  37, 132],
       [ 39,   5,   5,   9,  64, 122]])

**Q-3: Find unique arrays from a 2D array column wise and row wise.**
1. arr = np.array([[1,2,3,3,1,1],
2.               [0,9,1,2,8,8],
3.               [1,2,3,8,8,8],
4.               [1,2,3,3,1,1]])

In [ ]:

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [60]:
# rows 
np.unique(arr ,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [61]:
# cols
np.unique(arr,axis= 0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

**Q-4: Flip given 2-D array along both axes at the same time.**

In [65]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
np.flip(arr)

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [70]:
# OR 
arr[::-1 ,::-1]

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

**Q-5: Get row numbers of NumPy array having element larger than X.**
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

**X = 6**

In [110]:
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] )
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [93]:
x = 6 
np.where(np.any(arr > x , axis= 1))  # IMP 
arr.flatten()

array([ 1,  2,  3,  4,  5, 10, -3, 30,  4,  5,  3,  2,  5, -4,  5,  9,  7,
        3,  6,  5])

**Q-7: You are given a array. 
You have to find the minimum and maximum array element and remove that from the array.**

In [105]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [ ]:
minIndex = arr.argmin(axis = 1) # axis is optional 
maxIndex = arr.argmax(axis=1)
np.delete(arr , (minIndex , maxIndex) ,axis=1)



array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
        782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
        308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
        230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
        227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
        575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
        525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
        786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
        453, 193, 607, 677, 637, 728, 724, 534, 748

In [109]:
arr = np.array([[1,2,3],
               [5,6,7]])
np.delete(arr , [1] , axis=1)


array([[1, 3],
       [5, 7]])