In [3]:
import numpy as np 

In [4]:
a , b = map(int,input().split())
numpy_array = np.random.rand(a,b)
print(numpy_array)
print("Average : {}".format(np.mean(numpy_array)))

[[0.47283783 0.19749642]]
Average : 0.3351671251284642


**Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.**

In [5]:
def create_2darr(a , b):
    x = np.ones((a,b))
    x[1:-1 , 1:-1] = 0
    print(x)
create_2darr(4,4)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.**

In [6]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
np.eye(3) # OR
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# BUT
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.**

In [9]:
x = np.random.randint(0,4 ,size=5)
print(x)
np.vstack([x for _ in range(5)])

[2 2 2 3 1]


array([[2, 2, 2, 3, 1],
       [2, 2, 2, 3, 1],
       [2, 2, 2, 3, 1],
       [2, 2, 2, 3, 1],
       [2, 2, 2, 3, 1]], dtype=int32)

In [10]:
x = np.linspace(0,4,5)
x = np.vstack([x for _ in range(5)])
x

# OR
x = np.zeros((5,5))
x += np.arange(0,5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.**

**point** = np.array([2,3])

In [11]:
x = np.random.randint(1,100 , (10,2))
p = np.array([2,3])
# sqrt ( (x1 - x2)^2 + (y1 - y2)^2 ) 
ans = np.sqrt(np.sum((x-p)**2 , axis=1 )).astype(int)
print(ans)

[ 90 104  74  69  45  48 127  43  16  58]


In [12]:
index = np.unravel_index(99 ,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


In [13]:
x = input().split()
numpy_array = np.array(x[::-1] , dtype=float)
numpy_array

array([2., 1.])

# Softmax function
**Softmax function is a  fuction used in neural neworks to  create probability distribution on outer layer rather than on hidden layers like other functions do . The distribution works for negative numbers also , for almost equal distributions and enhances the result for an AI model to predict more clearly**

**Q-11: Softmax function**
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

In [14]:
# Practice 
softmax_array = np.array([86.03331084 ,37.7285648 , 48.64908087 ,87.16563062 ,38.40852563 ,37.20006318])
x = np.exp(softmax_array[0])/np.sum(np.exp(softmax_array)) 
print(f"{x:.8e}")
print(type(softmax_array))

2.43733248e-01
<class 'numpy.ndarray'>


In [15]:
# Solution
def find_softmax(array): # -> probaility distribution  
     if(not isinstance(array ,np.ndarray)):
         raise TypeError("Not a numpy array is passed to the function")
     elif array.ndim > 1:
         raise TypeError("Array must be 1d")
     else:
         x = np.exp(softmax_array)/np.sum(np.exp(softmax_array)) 
         return x
try:
  test1 = find_softmax(softmax_array)
except TypeError as e:
    print(e)
else:
    print(test1)
finally:
    print("Test case 1 is processed ")


[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
Test case 1 is processed 


In [16]:
def stack(*args):
    if not all (isinstance(i , np.ndarray) for i in args):
        raise TypeError("Only numpy arrays are allowed!")
    if not args:
        raise ValueError("At least one array must be provided")
    base_check = np.atleast_2d(args[0]).shape[1:]
    if all(np.atleast_2d(i).shape[1:] == base_check for i in args[1:]):
        return np.vstack(args)
    else:
        raise ValueError("Dimensions of all arrays must be same")

try:
   a = [[0, 1, 2, 3, 4], [5 ,6, 7, 8, 9]]
   b = [[1, 1 ,1, 1, 1] ,
   [1 ,1 ,1 ,1 ,1]]

   testcase_1 = stack(np.array(a) , np.array(b))
except TypeError as e:
    print(e)
except ValueError as j:
    print(j)
else:
    print(testcase_1)
finally:
    print("Test case 1 proceeded")



[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Test case 1 proceeded


In [17]:
# we cann't subtract 1d from 2d
x = np.random.rand(5,4) 
xmean = x.mean(axis=1 ,keepdims=True) # keepdims 
x - xmean

array([[-0.32674699,  0.30577142,  0.34269615, -0.32172058],
       [-0.03176592, -0.53843825,  0.31064716,  0.259557  ],
       [ 0.24133964, -0.25999599,  0.30893261, -0.29027626],
       [ 0.1239603 ,  0.22712598,  0.06853373, -0.41962001],
       [-0.29487407,  0.08064962,  0.15780039,  0.05642406]])

In [18]:
# keepdims keep  original dimensions of matrix
x.mean(axis=1 , keepdims=True)

array([[0.33776661],
       [0.5664726 ],
       [0.538365  ],
       [0.44033007],
       [0.70867813]])

In [19]:
 # SWAPPING COLUMNS 
x = np.arange(9).reshape(3,3)
# x[: ,0],x[:,1] = x[:,1],x[:,0] # will not work 
a = 1 
b = 3
a,b = b,a # this is valid 
x = x[: , [0,2,1]]
x

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [20]:
x = np.arange(9).reshape(3,3)
#print(x)
#  x[0],x[2] = x[2],x[0] # works fine -> permanant
# but for temporary
print(x[[2,1,0] , :]) # used in Machine Learning to do some tasks
print(x)



[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
x = [[1,2,3],[5,6,7], [8,9,0]] # works in list
x[0],x[2] = x[2],x[0]
x

[[8, 9, 0], [5, 6, 7], [1, 2, 3]]

In [22]:
matrix = np.arange(9).reshape(3,3)
matrix[matrix & 1 == 1] = -1
matrix

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

In [23]:
# in numpy logical operators don't work -> use .any or .all if needed 
a = np.array([1,2,3,4,5])
a[(a < 2) | (a > 4)]



array([1, 5])

In [24]:
print([1,2] and []) # in and first item is true and 2nd is false so short_circuit and return first item
print([] or [1,2]) # latest value as answer if true 
print([1,2] and [3,4])

[]
[1, 2]
[3, 4]


**Q-17: Given two arrays of same shape make an array of max out of two arrays.**
(Numpy way)
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]

In [25]:
# We can pass mutiple arrays inside an iterable 
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
np.max((a,b) , axis=0) 
# OR
np.max([a,b] , axis=0) # temporary

array([6, 3, 1, 7, 8])

In [26]:
# PERMANANT CHANGE IN a
mask = b > a # a ki wo values jin ke against b ki value > he us me b ki wo wali values dal do 
print(a[mask])
print(b[mask])
a[mask] = b[mask] 
a




[5]
[7]


array([6, 3, 1, 7, 8])

In [27]:
# np.where(condition, value_if_true, value_if_false)
x = np.where(b > a, b, a)
x

array([6, 3, 1, 7, 8])

In [28]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7483, 3658, 9752, 3412, 5752],
       [8599, 8908, 4556, 4513, 5799],
       [9177, 1543,   96, 9915, 4420],
       [5419, 1783, 3143, 1866, 2429],
       [5950, 1444, 3094, 2785, 2300],
       [6355, 4152, 9092, 5467, 4687],
       [2496, 7187, 4625,   91, 7293],
       [4015, 8155, 9373,  630, 2625]], dtype=int32)

In [29]:
arr1[: , ::2]

array([[7483, 9752, 5752],
       [8599, 4556, 5799],
       [9177,   96, 4420],
       [5419, 3143, 2429],
       [5950, 3094, 2300],
       [6355, 9092, 4687],
       [2496, 4625, 7293],
       [4015, 9373, 2625]], dtype=int32)

**Normalise the given array**
There are different form of normalisation for this question use below formula.

**Xnormalized = X−Xmin / Xmax−Xmin**

In [30]:
arr1Norm = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
arr1Norm

array([[7.52442997e-01, 3.63090391e-01, 9.83407980e-01, 3.38049674e-01,
        5.76241857e-01],
       [8.66042345e-01, 8.97495928e-01, 4.54499186e-01, 4.50122150e-01,
        5.81026059e-01],
       [9.24877850e-01, 1.47801303e-01, 5.08957655e-04, 1.00000000e+00,
        4.40655537e-01],
       [5.42345277e-01, 1.72231270e-01, 3.10667752e-01, 1.80679967e-01,
        2.37988599e-01],
       [5.96396580e-01, 1.37723941e-01, 3.05679967e-01, 2.74226384e-01,
        2.24857492e-01],
       [6.37622150e-01, 4.13375407e-01, 9.16225570e-01, 5.47231270e-01,
        4.67833876e-01],
       [2.44808632e-01, 7.22312704e-01, 4.61522801e-01, 0.00000000e+00,
        7.33102606e-01],
       [3.99429967e-01, 8.20846906e-01, 9.44828990e-01, 5.48656352e-02,
        2.57939739e-01]])

**Q-19: Write a function which will accept 2 arguments.**

**First:** A 1D numpy array arr
**Second:** An integer n {Please make sure n<=len(arr)}

**Output:** The output should be the nth largest item out of the array

**Example1** : arr=(12,34,40,7,1,0) and n=3, the output should be 12
**Example2** : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [32]:
def nth_largest(arr , n):
    if not isinstance(arr , np.ndarray) or arr.ndim != 1:
        raise TypeError("Not a numpy array is given ")
    if n > arr.size :
        raise ValueError("the number should be less than equal to  size of numpy array")
    return np.partition(arr , -n)[-n]
    

In [34]:
print(nth_largest(np.array([3,2,5,4,1]) , 2))


4


In [39]:
a = np.array([1,2,3])
np.hstack((np.repeat(a,3),
np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
np.array([[1,2] , [3,4]]).reshape(4)
# np.array([[1,2] , [3,4] , [5,6]]).reshape(2,3)

array([1, 2, 3, 4])

In [50]:
np.ones(4)

array([1., 1., 1., 1.])

In [73]:
x = np.array([[1,2],
              [3,4]])
np.max(x , axis=1 ,keepdims=True)



array([[2],
       [4]])

In [83]:
np.hsplit(x ,2 )

[array([[1],
        [3]]),
 array([[2],
        [4]])]